AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SkillStudio-Service-Deployment-Descriptor

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: java11
    MemorySize: 1024
    Timeout: 20
    AutoPublishAlias: !Ref Stage
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    CodeUri: ./application
    Tags:
      Stage: !Ref Stage
      Service: SkillStudio
      Resource: Lambda
    Environment:
      Variables:
        TABLE: !Ref SkillStudioTable
        APPLICATION_ENVIRONMENT: !Ref Stage
        CLOUD_REGION: us-east-1
        MAIN_CLASS: com.tekcapzule.skillstudio.application.SkillStudioApplication
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:

  # Setup API Gateway

  SkillStudioApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "skillstudio-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For, Content-Type, Authorization, X-User-Login, X-Channel-Code'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false
      Variables:
        LAMBDA_ALIAS: !Ref Stage

  # Setup DynamoDB Table

  SkillStudioTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}SkillStudio"
      AttributeDefinitions:
        - AttributeName: learningMaterialId
          AttributeType: S
        - AttributeName: topicCode
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: recommendations
          AttributeType: N
      KeySchema:
        - AttributeName: learningMaterialId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: topicGSI
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: topicCode
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
  # Setup Lambda Functions

  CreateLearningMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-SkillStudio-CreateLearningMaterial"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SkillStudioTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: createLearningMaterialFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: learning-material/create
            Method: post
            RestApiId:
              Ref: SkillStudioApi

  UpdateLearningMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-SkillStudio-UpdateLearningMaterial"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SkillStudioTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: updateLearningMaterialFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: learning-material/update
            Method: post
            RestApiId:
              Ref: SkillStudioApi

  GetLearningMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-SkillStudio-GetLearningMaterial"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SkillStudioTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getLearningMaterialFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: learning-material/get
            Method: post
            RestApiId:
              Ref: SkillStudioApi

  GetAllLearningMaterialsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-SkillStudio-GetAllLearningMaterial"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SkillStudioTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getAllLearningMaterialFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: learning-material/getAll
            Method: post
            RestApiId:
              Ref: SkillStudioApi

  RecommendLearningMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-SkillStudio-RecommendLearningMaterial"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SkillStudioTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: recommendLearningMaterialFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: learning-material/recommend
            Method: post
            RestApiId:
              Ref: SkillStudioApi

  ApproveLearningMaterialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-SkillStudio-ApproveLearningMaterial"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SkillStudioTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: approveLearningMaterialFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: learning-material/approve
            Method: post
            RestApiId:
              Ref: SkillStudioApi

  # Set Output Variable

Outputs:
  ApiEndpoint:
    Description: "SkillStudio API endpoint."
    Value: !Sub "https://${SkillStudioApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/skillstudio"
